### ISSUE TITLE
Overlapping route

### ISSUE THREAD

**Issue by neyhuel** [HCESrl/laravel-swagger-api#13]
Hey you approach is awesome, but i have a problem with Routes:: and Api::

I have an implementation for check permissions with a middleware called check.permission. This middleware validate if the user logged in has permission for this route. Now, the problem is when the middleware return forbidden for this route, the API facade it's generating the same route and it's respond me

For example:
```php
Route::group(['middleware' => ['auth:api', 'check.permission']], function () {
   Route::post('permission-route', 'ExampĺeController@example');
});
```

```php
Api::apiKeySecurity ( 'bearer' )
    ->parameterName ( 'Authorization' )
    ->inHeader ();

Api::post('permission-route', 'ExampĺeController@example')->requiresAuth('bearer');
```

This look pretty good, but, when i use this from Swagger the middleware don't grant me a permission and the route defined from API facade respond me.

I think, how it's possible !!! The Api facade dont generate routes, but when i run `php artisan route: list` with all routes (with Route facade) commented yet i get the same route list without the commented routes, and yes, without the middleware check.permission.

I try add middleware as `Api::group(['prefix' => 'some-prefix', 'middleware' => 'check.permission']....` but its don't working anyway

PS: I hope explained myself. English is not my main language

**Comment by fsavina** [comment]
The API facade actually does generate routes (you should think it as a wrapper for the route facade).

Have you tried something like the following?

```
Api::post('permission-route', 'ExampĺeController@example')
   ->middleware(['auth:api', 'check.permission'])
   ->requiresAuth('bearer');
```

**Comment by neyhuel** [comment]
Yes, i tried add the middleware that you mention it, but doesn't work anyway. As I couldn't solve this issue, i decided to change the package for another, sorry brother.

**Comment by fsavina** [comment]
fair enough!
