### ISSUE TITLE
Use it with Routes

### ISSUE THREAD

**Issue by Kingmaddi** [HCESrl/laravel-swagger-api#2]
Hi,

can i use this with standard Routes?

**Comment by fsavina** [comment]
@Kingmaddi I don't understand. Can you give me an example?

**Comment by Kingmaddi** [comment]
I sorry for my bad explanation. So I mean, can I use it with Route:: (web.php) instead with Api:: (api.php)?

**Comment by fsavina** [comment]
No problem.
Using `Route::` will only create the routes. In order to automatically create the Swagger API and the documentation you need to use the `Api::` facade.
You are free to use the `Api` facade in any routes file, either `web.php` or `api.php`.
