### ISSUE TITLE
Incorrect versions example

### ISSUE THREAD

**Issue by jonaszkadziela** [HCESrl/laravel-swagger-api#5]
Hi everyone,

After experimenting with features of this package, I noticed that [versions example](https://github.com/HCESrl/laravel-swagger-api#versions) is incorrect.

---

### Problem
```php
Api::tag('v1', function() {
    Api::get('versioned-uri', 'Controller@action');
});
```
This code produces `api/versioned-uri` route instead of `api/v1/versioned-uri`.

### Fix

To resolve this issue `Api::tag` should be changed to `Api::version`.

---

Also, I would like to thank you for creating and maintaining this project. Compared to other swagger integration packages for Laravel, this one is way cleaner and easier to use.

**Comment by fsavina** [comment]
@jonaszkadziela thanks! we've fixed the example
