### ISSUE TITLE
Problem with deploying to a production server

### ISSUE THREAD

**Issue by jonaszkadziela** [HCESrl/laravel-swagger-api#6]
Hi everyone,

For a few hours, I was struggling with setting up Swagger documentation on a production server.

---

### Problem
The following error message was being shown when trying to load Swagger UI:

![Screenshot - Mixed content](https://user-images.githubusercontent.com/34022120/76692332-3ffcb200-6655-11ea-9894-4e9be472e3cb.png)

```
Mixed Content: The page at 'https://redacted.com/docs' was loaded over HTTPS, but requested an insecure script 'http://redacted.com/vendor/swagger-ui/swagger-ui-bundle.js'. This request has been blocked; the content must be served over HTTPS.
```

#### After researching a bit, I came to the following conclusions

`DocsController` does not care about `scheme` defined in `api` config when rendering `swagger-ui` view.

When loading scripts and styles in `swagger-ui` view, `asset()` helper is being used.

To determine if assets should be loaded via HTTP or HTTPS, it uses `Request->secure()` method (from laravel/framework).
This method calls internally `Request->isSecure()` (from symfony/http-foundation) which checks not only request's protocol but also whether it comes from trusted proxies.

### Possible fixes

1. Update documentation

    Perhaps the easiest fix is simply adjusting the comment for `scheme` in `api` config file.

    Currently, it states `The HTTP scheme through which the API is served.` which is misleading in my opinion.
    Additionally, a notice about this potential problem could be added to the `README` file.
    You could reference Laravel documentation about [configuring trusted proxies](https://laravel.com/docs/6.x/requests#configuring-trusted-proxies).

1. Change `DocsController` and `swagger-ui` view to take `scheme` config into account

    As far as I am concerned, in `DocsController@index` you pass `$secure` variable to `swagger-ui` view but never use it. Perhaps you could change `$secure` value to depend on the current `scheme` setting.

    Then in `swagger-ui` view when you call `asset()` helper, pass `$secure` as a second argument.

I believe this should fix the issue. If you have any questions, do not hesitate to contact me.

### Sources
* [Asset helper docs](https://laravel.com/docs/6.x/helpers#method-asset)
* [Asset helper source code](https://github.com/laravel/framework/blob/4ea67d1e563715f16ce4b7f09cf146d2277d2d74/src/Illuminate/Routing/UrlGenerator.php#L233)
* [Request->secure() method](https://github.com/laravel/framework/blob/6a7046f48847146a4323f63e8c8e9ab33ef0c6d8/src/Illuminate/Http/Request.php#L269)
* [Request->isSecure() method](https://github.com/symfony/http-foundation/blob/6fad901d92ba58dd7bebe0419b2cb5a6683f7f15/Request.php#L1126)

**Comment by fsavina** [comment]
Hi @jonaszkadziela, I agree that the `scheme` configuration is misleading. Its purpose is only of configuration of the Swagger UI interface, nothing to do with actual routes generation nor the assets urls. We are working on a new release that will use relative paths instead of the `asset` function and we'll correct both the readme and the config files to avoid misunderstandings and add the reference to the trusted proxies docs. Thanks for the contribution!

**Comment by jonaszkadziela** [comment]
@fsavina Thank you for recognizing the problem. It is great to hear that you are working towards a better solution

**Comment by fsavina** [comment]
@jonaszkadziela checkout the [v1.0.0](https://github.com/HCESrl/laravel-swagger-api/releases/tag/v1.0.0) release and the updated readme. Thanks!
