### ISSUE TITLE
No "securityDefinitions" support as of yet

### ISSUE THREAD

**Issue by jonaszkadziela** [HCESrl/laravel-swagger-api#7]
Hi everyone,

I noticed that right now there is no support for `securityDefinitions`. I believe this element is essential for almost every API.

Could you please consider prioritizing implementation of this feature?

It seems that `Calcinai\Strut\Swagger`, which you use internally, already supports  `securityDefinitions`. This means it should not be a big hustle to implement.

I would be very grateful if you could do it.

**Comment by fsavina** [comment]
@jonaszkadziela we'll look into that, thanks for the suggestion!

**Comment by fsavina** [comment]
@jonaszkadziela [v1.2.0](https://github.com/HCESrl/laravel-swagger-api/releases/tag/v1.2.0) introduces support for security definitions!
