### ISSUE TITLE
Bearer Authentication Method

### ISSUE THREAD

**Issue by neyhuel** [HCESrl/laravel-swagger-api#8]
Its not possible create a native Bearer authentication. I had to use apiKeySecurity adapted to Bearer method, concatenating "Bearer" to the token string on SwaggerUI Authorize form

This is my code:
```php
Api::apiKeySecurity ( 'bearer' )
    ->parameterName ( 'Authorization' )
    ->inHeader ();
```

**Comment by fsavina** [comment]
bearer auth is part of OpenApi v3 specification. This package is based on the v2 specification. We'll definetely add that in the next version
